language: objective-c  #1
osx_image: xcode10.1 #2
script:
    - xcodebuild -scheme AcronymFinder -sdk iphonesimulator12.1 -destination "platform=iOS Simulator,OS=12.1,name=iPhone Xs Max" -UseModernBuildSystem=NO test | xcpretty --test --color; test ${PIPESTATUS[0]} -eq 0


#xcode_project: AcronymFinder.xcodeproj #3
#xcode_scheme: AcronymFinder #4
#xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
#xcode_sdk: iphonesimulator10.1 #5
