language: objective-c  #1
osx_image: xcode10.1 #2
xcode_project: AcronymFinder.xcodeproj #3
xcode_scheme: AcronymFinder #4
#xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
#xcode_sdk: iphonesimulator10.1 #5
